name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List frontend content (debug)
        run: ls -la frontend/

      - name: Copy frontend folder to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: frontend/
          target: /srv/docker/docker-sdv-devideas/frontend
          strip_components: 1

      - name: Copy backend_data folder to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: backend_data/
          target: /srv/docker/docker-sdv-devideas/backend_data
          strip_components: 1

      - name: Copy backend docker-compose and backend files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: |
            docker-compose.yml
            backend/
          target: /srv/docker/docker-sdv-devideas/
          strip_components: 0

      - name: Restart docker-compose on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /srv/docker/docker-sdv-devideas
            docker-compose pull
            docker-compose up -d --build
            docker system prune -f
